image: node:16

stages: 
  - install
  - coana

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

coana-ci:
  stage: coana
  image: coana/coana:latest 
  dependencies:
    - install
  script:
    - coana . -o output.json
  artifacts:
    paths:
      - output.json
