image: node:16

stages: 
  - install
  - coana

build:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

coana-ci:
  stage: coana
  image: coana/coana:v1.0 
  dependencies:
    - install
  script:
    - coana . -o output.json
  artifacts:
    paths:
      - output.json